---


- hosts: all:!proxy
  remote_user: '{{common.normal_user}}'
  gather_facts: False
  roles:
    - agent_uninstall
    - agent_install
  tags:
    - agent_install

- hosts: proxy
  remote_user: '{{common.normal_user}}'
  gather_facts: False
  roles:
    - proxy_install
  tags:
    - proxy_install

- hosts: all:!proxy
  remote_user: '{{common.normal_user}}'
  gather_facts: False
  roles:
    - agent_uninstall
  tags:
    - agent_uninstall
