---

#- hosts: '{{ target_hosts }}'
#- hosts: all
#  remote_user: '{{common.root_user}}'
#  gather_facts: False
#  tasks:
#    - name: get date
#      shell: date

- hosts: all:!proxy
  remote_user: '{{common.root_user}}'
  gather_facts: False
  roles:
    - agent_uninstall
    - agent_install
  tags:
    - agent_install

- hosts: proxy
  remote_user: '{{common.root_user}}'
  gather_facts: False
  roles:
    - proxy_install
  tags:
    - proxy_install

- hosts: all:!proxy
  remote_user: '{{common.root_user}}'
  gather_facts: False
  roles:
    - agent_uninstall
  tags:
    - agent_uninstall
