---

- name: uninstall agent
  include: roles/agent_uninstall/tasks/main.yml

- name: install agent
  include: roles/agent_install/tasks/main.yml

- name: download the installation script
  get_url:
    url: "{{proxy.download_url}}"
    dest: "{{proxy.install_file}}"
    force: yes
    mode: 0700

- name: modify serer_ip for {{proxy.install_file}}
  shell: sed -ri '/^\bserver_ip=/c\server_ip="{{server_ip}}"' "{{proxy.install_file}}" 
  when: is_mapping_network

- name: execute the installation script
  shell: sh "{{proxy.install_file}}"
  async: 300
  poll: 10
  sudo: yes
  register: proxy_install

- name: proxy install stdout
  debug: var=proxy_install.stdout_lines
  when: proxy_install is defined
